# Generated by Django 3.2 on 2021-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
